name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: 
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: blacklisten/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 3dd5cec5fa368b69e6a0aa1a89896d85
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
